# Starter pipeline
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'demoARM'
    subscriptionId: '2bd94ec0-b962-4bad-84a8-7900bb20b520'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'GajananaRG'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://github.com/gajananaHUB/appservice.git'
    csmParametersFileLink: 'https://github.com/gajananaHUB/appservice.git'
    deploymentMode: 'Incremental'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
